import Metrics from './metrics';

// export const COLORS = {
//   white: '#ffffff',
//   backgroundLight: '#E5E5E5',
//   background: '#F1EDED',
//   textTitle: '#042C5C',
//   textDarkGrey: '#4F4F4F',
//   buttonBlue: '#478DF7',
//   transparent: 'transparent',
//   border: '#012B72',
//   green: '#2AD95A',
//   red: '#EB5757',
//   blue: '#478DF7',
//   textBlue: '#0047CC',
//   lightBlue: '#78AAF1',
//   darkBlue: '#012B72',
//   borderMessage: '#E0E0E0',
//   buttonDisabled: '#B4D1F9',
//   greyBlue: '#66829B',
//   lightGreen: '#EAF9F2',
//   tabBackground: '#F2F2F2',
//   placeholder: '#D8D8D8',
//   alertBlue: '#E7EFFB',
//   dropDown: '#E6E8ED',
//   lightGrey: '#F6F6F6',
//   darkGreen: '#27AE60',
//   grey: '#8A9199',
//   darkGrey: '#BDBDBD',
//   black: '#000000',
//   eightTwo: '#828282',
//   lightRed: '#FF6A6A',
//   textFieldBackground: '#F8F8FA',
//   lightInfo: '#488CF6',
//   tranparentBlue: '#EFF5FF',
//   txtBackgroundColor: '#d4d2d2',
//   modalHeaderBackground: '#FAFAF8',
//   checkboxUnselect: '#676F7F',
//   checkboxFill: 'rgba(0, 0, 0, 0.54)',
//   backgroundColor: '#F8F8FA',
//   radioButtonOuter: '#E3E5E9',
//   lockUnlockColor: '#012B72',
//   lightGreen: '#BCEECA',
//   purple: '#C3BCEE',
//   lightGreyColor: '#77869E',
//   sectionBorder: '#E3E5E9',
//   transaction: '#012B72',
//   tranBackColor: '#232F3E',
//   lightWhite: '#F3F3F3',
//   arrowColor: '#C9C9C9',
//   calenderBlue: '#D9E8FB',
//   acceptDeclineBackgroundColor: '#F1F3FB',
//   grayBase: '#C7C7CC',
//   grayDark: '#333333',
//   mainBG: '#F8F8FA',
//   text: '#071B32'
// };

export const FONT_SIZE = {
  very_tiny: Metrics.rfv(6),
  tiny: Metrics.rfv(8),
  small_tiny: Metrics.rfv(10),
  small: Metrics.rfv(12),
  small_medium: Metrics.rfv(14),
  medium: Metrics.rfv(16),
  medium_extra: Metrics.rfv(18),
  regular: Metrics.rfv(20),
  large: Metrics.rfv(24),
  extra_large: Metrics.rfv(48)
};

export const HIT_SLOP = {
  top: 20,
  left: 20,
  right: 20,
  bottom: 20
};
